// Verifies that every race in notes/councillor-election-structure.csv lets a
// voter mark exactly as many names as the contest fills seats —
// seats_per_district equals max_votes, row for row.
//
// The two columns measure different things, and are maintained separately:
// seats_per_district is district magnitude, max_votes is the ballot
// instruction, cited on its own in max_votes_source (see notes/SOURCES.md,
// "ward_type and block_vote measure different things"). They coincide today
// only because every contest in the study is either single-seat or
// plurality-at-large, where votes equal seats by construction.
//
// So this is a tripwire, not a law. A failure means one of two things, and both
// want a human: a typo in one of the two columns, or a municipality has
// genuinely adopted a ballot where seats and votes diverge — limited or
// cumulative voting — which the survey's vote-for-N wording would then have to
// handle rather than derive from seat counts.
//
// The CSV is generated by scripts/get-municipal-data.R from
// notes/council-races.csv, so a failure is fixed in that hand-maintained file
// and the generator rerun, not by editing the CSV.
//
// Run from the repo root with:  node --test
// (or point at this file directly; `node --test <dir>` is not supported)

const test = require("node:test");
const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const path = require("node:path");

const CSV_PATH = path.join(
  __dirname,
  "../notes/councillor-election-structure.csv",
);

// Minimal RFC 4180 splitter. Needed because `office` values are quoted and
// contain commas (ex: "Councillor, Regional"), which naive splitting would
// shift every later column past.
function parseCsvLine(line) {
  const fields = [];
  let field = "";
  let in_quotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (in_quotes) {
      if (ch !== '"') {
        field += ch;
      } else if (line[i + 1] === '"') {
        field += '"';
        i++;
      } else {
        in_quotes = false;
      }
    } else if (ch === '"') {
      in_quotes = true;
    } else if (ch === ",") {
      fields.push(field);
      field = "";
    } else {
      field += ch;
    }
  }
  fields.push(field);
  return fields;
}

// Returns { header, rows }, one row object per line keyed by column name.
//
// `header` comes back alongside the rows so the test can assert the columns it
// depends on are really there. A renamed column otherwise reads back as
// undefined on every row, and the comparison below would pass on
// undefined === undefined without ever looking at the data.
function readStructureCsv() {
  const raw = readFileSync(CSV_PATH, "utf8");
  const lines = raw.split(/\r?\n/).filter((line) => line.trim() !== "");
  const header = parseCsvLine(lines[0]);
  const rows = lines.slice(1).map((line) => {
    const fields = parseCsvLine(line);
    return Object.fromEntries(header.map((name, i) => [name, fields[i]]));
  });
  return { header, rows };
}

// Both columns are small positive counts. Parsing them, rather than comparing
// the raw strings, keeps the check from being satisfied by two blanks or by two
// copies of the same typo'd non-number — those become failures in their own
// right instead of a silent equality.
function parseCount(value) {
  const text = (value ?? "").trim();
  if (!/^\d+$/.test(text)) return null;
  const count = Number(text);
  return count > 0 ? count : null;
}

test("every race in the structure CSV fills as many seats as a voter can mark", () => {
  const { header, rows } = readStructureCsv();

  for (const column of ["csdname", "office", "seats_per_district", "max_votes"]) {
    assert.ok(header.includes(column), "no " + column + " column in " + CSV_PATH);
  }

  // A parse that dropped every row would satisfy the comparison below without
  // reading a single value.
  assert.ok(rows.length > 0, "no data rows in " + CSV_PATH);

  const mismatched = [];
  for (const row of rows) {
    const seats = parseCount(row.seats_per_district);
    const votes = parseCount(row.max_votes);
    const where = row.csdname + " — " + row.office + ": ";

    if (seats === null || votes === null) {
      mismatched.push(
        where +
          "seats_per_district=" +
          JSON.stringify(row.seats_per_district) +
          ", max_votes=" +
          JSON.stringify(row.max_votes) +
          " (expected positive integers)",
      );
    } else if (seats !== votes) {
      mismatched.push(
        where + "seats_per_district=" + seats + ", max_votes=" + votes,
      );
    }
  }

  assert.deepEqual(
    mismatched,
    [],
    "seats_per_district and max_votes disagree in " +
      CSV_PATH +
      "\n  " +
      mismatched.join("\n  "),
  );
});
