#!/usr/bin/env python3
"""Build notes/contest-candidate-counts.csv: one row per contest, with its candidate count.

Usage: python3 scripts/build-contest-candidate-counts.py

Takes no arguments and, like the other scripts here, resolves the repo root from its own
path so it can be run from any working directory. Needs no third-party packages.

Input
  data/raw/candidates-raw.json
      Generated by scripts/build-candidates-raw.py. Rebuild that first; this script only
      counts what is already there and adds nothing of its own.

Output
  notes/contest-candidate-counts.csv
      Generated - do not hand-edit. One row per district in that file, which is the grain a
      voter actually sees: Ottawa's councillor race is 24 rows, one per ward, not one row of
      68. Coarser tables are a group-by away - by (census_id, office) for the race grain of
      notes/councillor-election-structure.csv, by census_id for the municipality.

Rows are sorted by candidate count, largest first, so the contests with the most names on
the ballot are at the top. Ties fall back to the ballot order a voter would see, so the
sort is stable across runs.

A row is keyed by (census_id, office, district), which is unique: the two races that share
an office anywhere in this data are Chatham-Kent's ward tiers, and they hold different
wards. The ballot structure of the parent race - how many districts it has, its seats and
its max_votes - is not repeated here; it is in notes/councillor-election-structure.csv,
one join on census_id + office away.

The counts are a snapshot, not a final tally: nominations close 2026-08-21 and the
certified lists follow on 2026-08-24, so every count here is a lower bound until then. The
retrieved column carries the date each municipality's list was read, so a stale row is
visible rather than implied.
"""
import csv
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "data", "raw", "candidates-raw.json")
DEST = os.path.join(REPO, "notes", "contest-candidate-counts.csv")

# Ballot order, so a municipality's rows read the way its ballot does rather than
# alphabetically by race key.
RACE_ORDER = ["mayor", "deputy mayor", "atlarge", "regional councillor", "ward"]

FIELDS = [
    "census_id",
    "csdname",
    "race",
    "office",
    "district_scope",
    "district",
    "n_candidates",
    "retrieved",
]

with open(SRC, encoding="utf-8") as fh:
    doc = json.load(fh)

rows = []
for census_id, mun in doc.items():
    if census_id == "_meta":
        continue
    for race_key, races in mun["races"].items():
        for race in races:
            # Districts keep the order the source published them in - Ward 1, Ward 2, ...,
            # Ward 10 - which sorting the names would break.
            for position, (district, contest) in enumerate(race["districts"].items()):
                rows.append(
                    {
                        "census_id": census_id,
                        "csdname": mun["csdname"],
                        "race": race_key,
                        "office": race["office"],
                        "district_scope": race["district_scope"],
                        "district": district,
                        "n_candidates": len(contest["candidates"]),
                        "retrieved": mun["notes"]["retrieved"],
                        # Dropped before the file is written: these order the rows and
                        # count the races in the summary, but are the parent race's
                        # attributes rather than the contest's.
                        "_n_districts": race["n_districts"],
                        "_position": position,
                    }
                )

# Largest field first. Everything after the count is the tie-break: a municipality's tied
# contests stay in ballot order rather than moving between runs.
rows.sort(
    key=lambda r: (
        -r["n_candidates"],
        r["csdname"],
        RACE_ORDER.index(r["race"]) if r["race"] in RACE_ORDER else len(RACE_ORDER),
        r["office"],
        r["_n_districts"],
        r["_position"],
    )
)

keys = [(r["census_id"], r["office"], r["district"]) for r in rows]
if len(set(keys)) != len(keys):
    dupes = sorted({k for k in keys if keys.count(k) > 1})
    sys.exit(
        "census_id + office + district is not unique, so the rows cannot be told apart:\n"
        + "\n".join(f"  {k}" for k in dupes)
    )

n_races = len({(r["census_id"], r["office"], r["_n_districts"]) for r in rows})
for row in rows:
    del row["_n_districts"]
    del row["_position"]

with open(DEST, "w", encoding="utf-8", newline="") as fh:
    writer = csv.DictWriter(fh, fieldnames=FIELDS)
    writer.writeheader()
    writer.writerows(rows)

print(f"wrote {os.path.relpath(DEST, REPO)}")
print(
    f"  contests {len(rows)}"
    f"  races {n_races}"
    f"  municipalities {len({r['census_id'] for r in rows})}"
    f"  candidates {sum(r['n_candidates'] for r in rows)}"
)
