#!/usr/bin/env python3
"""Build the survey-facing candidate file from data/raw/candidates-raw.json.

Usage: python3 scripts/build-candidates-js.py

Takes no arguments and, like the other scripts here, resolves the repo root from its own
path so it can be run from any working directory.

Inputs
  data/raw/candidates-raw.json
      Generated by scripts/build-candidates-raw.py. The source of truth for candidates.
  data/candidate-data-versions/version.txt
      The version number to stamp into the filename and into meta.version.

Output
  data/candidate-data-versions/candidates-{YYYY-MM-DD}-v{VERSION}.js
      Assigns a nested object to window.CMB_CANDIDATES. Loaded by the survey header and
      read by code/survey/parse-candidates.js in the survey repo.

The file is a lookup table, not a description of the elections: everything the survey
writes is worked out here, once, and stored under the municipality and ward that produce
it. The survey then reads one entry and writes it out. Anything that has to be *decided* -
which races a respondent is served, how their names merge and sort, whether a race is
acclaimed, how many names they may mark, what shape their ballot is - is decided here.

  window.CMB_CANDIDATES = {
    meta: {...},
    municipalities: {
      "<census_id>": {
        name: "Ottawa",
        shared: {
          names:  { mayor: [...], coun_atlarge: [...], dep_mayor: [...] },
          fields: { mayor_accl: 0, atlarge: 1, atlarge_accl: 0, ... }
        },
        wards: {
          "<ward label>"|"99": {
            names:  { coun_ward: [...], coun_reg: [...] },
            fields: { ward: 1, ward_accl: 0, ward_max_votes: 1, ... }
          }
        }
      }
    }
  };

An entry comes in two halves. `shared` is what the municipality decides for every ward
alike - the mayoral, at-large councillor and deputy mayor races - held once instead of
repeated in each of Toronto's 26 entries; the ward entry holds the rest. The two are
disjoint, so the survey writes both and each field lands exactly once, and which half a
field falls in changes nothing about the export. See SHARED_STEMS.

`names` holds "LAST, First" in the order they should appear. `fields` holds every scalar
the survey writes, already in its final form - a number, or "" where there is nothing to
say. Every ward entry carries the same `fields` keys, so nothing can go stale. Every stem
produces `<stem>_accl` and the numbered name fields the survey writes from `names`; the
three stems that can put more than one name on a ballot add `<stem>_max_votes`. A blank in
either family is how the survey flow knows the respondent has no such race, so it means
that and nothing else - an unverified seat count aborts the build rather than writing one.
The three councillor stems also carry a bare `<stem>` served-flag, which says what a blank
accl says and is kept anyway because the flow reads better for it. Add a stem and the
fields follow; the only lists of field names are SINGLE_VOTE_STEMS, which names the two
that omit max_votes, and SERVED_FLAG_STEMS, which names the three that add a flag.

Every municipality has a "99" ward entry as well as its real wards. It holds whatever is
decided at large - the mayor, the at-large councillors, and any at-large regional or
deputy mayor race - with an empty ward-councillor list, and is what a respondent gets if
they reach the question without a ward. For the three municipalities that elect entirely
at large it is the only entry, and `ward` is empty in it.

WHY IT IS SHAPED THIS WAY, rather than mirroring the races

  Five race stems, because the survey writes five families of embedded fields: mayor,
  ward, atlarge, reg_coun, dep_mayor. One stem is one contest as a voter meets it, so
  a ward councillor race and an at-large councillor race are never merged: they are
  different contests with their own candidates, their own max_votes and their own
  acclamation. See STEM below for the rule and what it costs.

  A respondent is served an at-large race, plus the one district of each ward race that
  they live in - never the municipality's other wards. So a Thunder Bay respondent gets
  their ward's single councillor under ward and the city's 5 at-large seats under
  atlarge, rather than one merged race for 6; not the 12 its seven wards would total
  either way. Sarnia has no wards and elects two city-wide slates of four, which are two
  contests and not one: its City councillors are atlarge, and its City-County
  councillors sit on Lambton County council as well and are reg_coun, the same stem every
  other upper-tier seat in the study uses.

  As the data stands every respondent is served at most one race per stem, so nothing is
  actually merged. The merge is still what a stem means - Chatham-Kent's two ward tiers
  are one stem, and a municipality that split its at-large council seats into two same-tier
  contests would be another - but a stem that starts merging different offices is a sign
  the office belongs in a stem of its own.

  A race is acclaimed when it has no more candidates than seats, which is not the same as
  having exactly one: thirteen races here fill more than one seat. Where a respondent is
  served several races under one stem, all of them must be decided before there is nothing
  left to ask.

  Seats filled and names a voter may mark are separate measures that coincide in every
  race in the study today - tests/structure-csv.test.js is the tripwire for that changing -
  so max_votes is read from max_votes and never stood in for by seats.

  Ward pairs are stored under each ward they are drawn from, so a respondent's single-ward
  answer finds their ballot. Brampton elects both its City and its Regional councillors
  from five pairs, and Clarington its Regional councillors from two. The rule is the one
  parse-wards.test.js already uses: take the numbers out of the label.

NAME ORDER is settled here, so the survey does not have to sort. The order is the one
JavaScript's localeCompare produces, reproduced by NAME_SORT_KEY below, because that is
what the survey used to call and what the ward and municipality lists elsewhere follow.
parse-candidates.test.js re-checks every emitted list against localeCompare itself, so the
two cannot drift apart silently.

The output is pure ASCII: non-ASCII characters are written as \\uXXXX escapes. The file is
served from GitHub Pages and loaded by a <script src> with no charset attribute, so the
browser is left to guess an encoding - and one wrong guess would turn "Ward 1 Orléans
East-Cumberland" into a string that no longer matches the ward the survey embedded.
"""
import json
import os
import re
import sys
import unicodedata
from datetime import date

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "data", "raw", "candidates-raw.json")
VERSIONS = os.path.join(REPO, "data", "candidate-data-versions")
VERSION_FILE = os.path.join(VERSIONS, "version.txt")

# Raw race key -> the embedded-field stem the survey writes for it.
#
# A councillor elected at large is its own stem, never folded into `ward`, because the two
# are separate contests: max_votes, acclamation and the candidate list are all scoped to
# the contest, and `ward` is scoped to one ward. Thunder Bay is the municipality that makes
# the difference visible - it runs both, and a respondent there marks 1 ward councillor and
# 5 at-large ones - but the split does not depend on that overlap. Niagara Falls, North Bay
# and Sarnia elect councillors only at large, and their lists are atlarge too, with
# `ward` empty. One rule, no municipality-shaped exceptions.
#
# A regional councillor keeps its own stem whether or not it is elected at large: it is a
# different office (upper-tier), not the same office on a wider ballot.
#
# The ward councillor stem is `ward` and not `coun`: its scalars sit next to the `ward`
# flag the flow filters on, so the family reads ward, ward_accl, ward_max_votes. Its
# candidate list is still coun_ward1.. - see NAME_FIELD, where the two part ways.
STEM = {
    "mayor": "mayor",
    "ward": "ward",
    "atlarge": "atlarge",
    "regional councillor": "reg_coun",
    "deputy mayor": "dep_mayor",
}
STEMS = ["mayor", "ward", "atlarge", "reg_coun", "dep_mayor"]

# The stem names the scalars; this names the numbered candidate fields, and for the three
# councillor races the two differ. The survey groups every councillor list under one
# prefix - coun_ward1, coun_atlarge1, coun_reg1 - so the three read as one office split
# three ways and sort together in the export, while the scalars stay short and say what
# the respondent is being asked: ward, atlarge, reg_coun. meta.stems carries this map,
# since nothing downstream can infer it - least of all `ward` -> `coun_ward`.
NAME_FIELD = {
    "mayor": "mayor",
    "ward": "coun_ward",
    "atlarge": "coun_atlarge",
    "reg_coun": "coun_reg",
    "dep_mayor": "dep_mayor",
}

# The stems that write no `<stem>_max_votes`, because the answer is always 1: a
# municipality elects one mayor, and one deputy mayor where the office is on the ballot at
# all. A column that reads 1 in every row for every respondent says nothing, and its
# presence alongside ward_max_votes and atlarge_max_votes implies it could have said
# something else - which is the confusion worth avoiding, since the whole point of the
# max_votes family is that it varies.
#
# `<stem>_accl` is still written for both: whether a respondent is served the race varies
# (only Innisfil and New Tecumseth elect a deputy mayor), and so does acclamation - Markham,
# Vaughan and Waterloo each had a single mayoral candidate on file when this was written.
# Neither carries a bare served-flag; see SERVED_FLAG_STEMS for why the three councillor
# stems do and these two do not.
#
# The assumption is checked rather than trusted, below: a race under one of these stems
# with a max_votes other than 1 aborts the build instead of quietly dropping the number.
SINGLE_VOTE_STEMS = {"mayor", "dep_mayor"}

# The stems that write a bare `<stem>` served-flag alongside their scalars: 1 where this
# respondent is served the race, 0 where they are not.
#
# The flag says nothing `<stem>_accl != ""` does not - that equivalence is pinned by the
# tests, and it is why the other served-flags were dropped once the flow began filtering on
# accl directly. It is back for the three councillor stems because of what the flow has to
# do with them. A respondent can be served any combination of the three, the questions are
# piped and shown per stem, and `__js_atlarge` reads as what it means to the next person to
# open the flow where `__js_atlarge_accl != ""` reads as a puzzle - "is a blank acclamation
# a race nobody won, or no race at all?". The answer is in this file's header and in the
# survey README, which is exactly where a flow editor is not looking.
#
# mayor and dep_mayor keep the derived reading. Not because the fact is any less true for
# them, but because neither is a choice between questions: every municipality in the study
# elects a mayor, so the flag would read 1 in every row, and the deputy mayor question is
# one question shown in two municipalities rather than one of a set to pick between.
#
# Whether that is worth the second spelling is a judgement about the flow, not about the
# data, which is why it lives in a set here rather than in the shape of the code. Adding a
# stem to this set adds its flag and nothing else.
SERVED_FLAG_STEMS = {"ward", "atlarge", "reg_coun"}

# The stems a municipality decides once for all of its wards, and which are therefore
# stored once under `shared` rather than repeated in every ward entry. Toronto's mayoral
# list was held 26 times over; the at-large councillor lists were the larger half of the
# same duplication, and Sarnia's fifteen names sat in every one of its entries.
#
# What makes a stem shareable is that its lists and scalars do not vary by ward, and every
# race under these three is elected municipality-wide: one mayor, one deputy mayor where
# the office exists, and at-large councillors in the municipalities that elect them. The
# assumption is checked rather than trusted - the projection below builds the shared half
# from each ward in turn and aborts if any two disagree, because storing it once would
# otherwise quietly serve one ward's answer to all of them.
#
# `reg_coun` is the near miss and stays per-ward: it is elected at large in 30 of the 38
# municipalities and by ward or ward-pair in the other 8, so the stem as a whole is not
# ward-invariant even though most of its races are. Splitting a stem across the two halves
# would break the one property parse-candidates.js relies on - that the halves are disjoint,
# so writing both in either order writes each field exactly once.
#
# Nothing about the export changes: the survey writes the union of the two halves, under
# the same field names as before. What changes is the size of the file the header loads.
SHARED_STEMS = {"mayor", "atlarge", "dep_mayor"}

# The key for "no ward" - both an at-large race's only district and the ward value sent
# when the ward question was skipped.
AT_LARGE = "99"

# parse-wards.js is the survey-facing name list and calls 3553005 "Greater Sudbury"; the
# census calls it "Greater Sudbury / Grand Sudbury". Matching is on census_id, so this is
# cosmetic - it keeps the console logs from the two scripts reading the same.
NAME_OVERRIDE = {"3553005": "Greater Sudbury"}

# The punctuation that appears in these names, in the order JavaScript's localeCompare
# puts it in, which is not the order their code points are in: it sorts hyphen before
# comma, and the typographic apostrophe next to the ASCII one rather than up above the
# letters. Derived by asking localeCompare to sort "A<p>A" for each character present.
# All of it sorts below any letter.
PUNCT_ORDER = " -,.'’()"
PUNCT_RANK = {c: i for i, c in enumerate(PUNCT_ORDER)}


def display_name(candidate):
    """"LAST, First" - or bare "LAST" where the source published no given name.

    Brampton lists one mayoral candidate as `Gursimranjit Singh, -`, a placeholder that
    make_candidate() in build-candidates-raw.py records as an empty first_name. Joining on
    ", " unconditionally turns that into "GURSIMRANJIT SINGH, ", and the separator then
    outlives the name it was meant to separate: the survey pipes these strings as choice
    text, so the respondent is shown a dangling comma, and parse-recognition.js matches the
    captured selections back against these same strings VERBATIM after trimming the
    capture - so the trailing space is trimmed off the last selection and the name no
    longer matches. It is dropped from `__js_recog_mayor*`, the count is one short, and the
    only sign is a console error no export ever carries. Hence: no first name, no comma.
    """
    last = candidate["last_name"]
    first = candidate["first_name"]
    return last + ", " + first if first else last


def name_sort_key(name):
    """Sort a "LAST, First" string the way JavaScript's localeCompare would.

    Accents fold onto the base letter, so GOLLÉ sits beside GOLLER rather than after Z;
    case folds away; punctuation keeps its own low ranks, so "ADAM, Rebecca" precedes
    "ADAMO, Jerome" and "GORDON-DANIELS" precedes "GORDON, Fitz-Roy". Verified against
    localeCompare over every name in the data, and re-checked by parse-candidates.test.js.
    """
    stripped = "".join(
        c for c in unicodedata.normalize("NFKD", name) if not unicodedata.combining(c)
    )
    weights = [
        (0, PUNCT_RANK[c]) if c in PUNCT_RANK else (1, c.upper()) for c in stripped
    ]
    # The raw string breaks ties the folding created, so the order is total.
    return (weights, name)


def die(*msgs):
    for m in msgs:
        print(f"Error: {m}", file=sys.stderr)
    sys.exit(1)


def split_ward_pair(label):
    """"Wards 1, 5" -> ["Ward 1", "Ward 5"]. Same rule as parse-wards.test.js."""
    return ["Ward " + n for n in re.findall(r"\d+", label)]


# --- serialisation ------------------------------------------------------------------
#
# json.dumps(indent=2) would give every name a line of its own, several thousand of them.
# Name lists are dumped compactly instead and spliced back in, so the file stays readable:
# one ward's list per line, the structure above it indented.
_COMPACT = {}


def compact(obj):
    key = f"@@compact:{len(_COMPACT)}@@"
    _COMPACT[key] = json.dumps(obj, ensure_ascii=True, separators=(", ", ": "))
    return key


def dump(obj):
    text = json.dumps(obj, indent=2, ensure_ascii=True)
    for key, value in _COMPACT.items():
        text = text.replace(json.dumps(key), value)
    return text


# --- read inputs --------------------------------------------------------------------

if not os.path.exists(SRC):
    die(f"no such file: {SRC}", "run scripts/build-candidates-raw.py first")

if not os.path.exists(VERSION_FILE):
    die(f"no such file: {VERSION_FILE}")

with open(SRC, encoding="utf-8") as fh:
    raw = json.load(fh)

with open(VERSION_FILE, encoding="utf-8") as fh:
    version = fh.read().strip()

if not version:
    die(f"no version number found in {VERSION_FILE}")

problems = []

# --- assemble the races, keyed by stem and district ---------------------------------
#
# An intermediate structure, not the output: it is what the projection below reads, and
# what the checks are easiest to state against.

races_by_mun = {}
mun_names = {}

for census_id in sorted(k for k in raw if k != "_meta"):
    entry = raw[census_id]
    mun_names[census_id] = NAME_OVERRIDE.get(census_id, entry["csdname"])
    races = {}

    for race_key, race_list in entry["races"].items():
        stem = STEM.get(race_key)
        if stem is None:
            problems.append(f"{census_id}: unknown race key {race_key!r}")
            continue

        for race in race_list:
            at_large = race.get("district_scope") == "At-large"
            seats = race.get("seats_per_district")
            # Seats filled and names a voter may mark are two different measures. See the
            # module docstring; both are carried so neither stands in for the other.
            max_votes = race.get("max_votes")
            if stem in SINGLE_VOTE_STEMS and max_votes not in (None, 1):
                problems.append(
                    f"{census_id}: {race_key} has max_votes {max_votes}, but {stem} "
                    f"writes no {stem}_max_votes field, on the assumption that it is "
                    "always 1 - see SINGLE_VOTE_STEMS"
                )
            districts = {}

            for label, district in race["districts"].items():
                names = sorted(
                    (display_name(c) for c in district["candidates"]),
                    key=name_sort_key,
                )
                for name in names:
                    # A name the survey can show and read back. These strings are the
                    # recognition questions' choice text and are matched back verbatim, so
                    # an edge space or a separator with nothing after it is both a visible
                    # blemish and a silent parse failure - see display_name().
                    if name != name.strip() or name.startswith(",") or name.endswith(","):
                        problems.append(
                            f"{census_id}: {name!r} is not a well-formed display name - it "
                            "carries an edge space or a separator with no name after it. "
                            "The survey shows these strings to respondents and matches "
                            "them back verbatim; see display_name()."
                        )
                    for ch in name:
                        if not ch.isalnum() and ch not in PUNCT_RANK:
                            problems.append(
                                f"{census_id}: {name!r} contains {ch!r} (U+{ord(ch):04X}), "
                                "which has no rank in PUNCT_ORDER, so its sort position "
                                "would not match localeCompare"
                            )
                record = {
                    "seats": seats,
                    "max_votes": max_votes,
                    "names": names,
                }
                # A race whose seat count is unverified upstream used to be served with a
                # blank accl, reported at the end of the run and left for a human to chase.
                # It cannot be any more: the flow now reads a blank accl as "no such race
                # here" and skips the question, so serving one would quietly hide a real
                # contest from the people who vote in it. Verify the seat count in
                # data/raw/by-municipality/, or drop the race into notes/excluded-races.csv
                # if the study is not asking about it.
                if seats is None or max_votes is None:
                    problems.append(
                        f"{census_id}: {race_key} district {label!r} has no verified "
                        f"{'seat count' if seats is None else 'max_votes'}, so its accl "
                        "and max_votes would be blank - which the flow now reads as 'no "
                        "such race'. Verify it, or exclude the race."
                    )

                # A ward pair is stored under each ward it is drawn from: a respondent
                # answers with the one they live in, and both look up the same ballot.
                if race.get("district_scope") == "Ward-pair":
                    wards = split_ward_pair(label)
                    if not wards:
                        problems.append(f"{census_id}: cannot split ward pair {label!r}")
                        continue
                    for ward in wards:
                        if ward in districts:
                            problems.append(
                                f"{census_id}: {race_key} district {ward!r} claimed twice "
                                f"(from {label!r})"
                            )
                        districts[ward] = record
                else:
                    key = AT_LARGE if at_large else label
                    if key in districts:
                        problems.append(
                            f"{census_id}: {race_key} district {key!r} claimed twice"
                        )
                    districts[key] = record

            races.setdefault(stem, []).append(
                {
                    "office": race["office"],
                    "at_large": at_large,
                    "districts": districts,
                }
            )

    if "mayor" not in races:
        problems.append(f"{census_id}: no mayoral race")
    # Either kind of councillor race satisfies this: a municipality that elects entirely at
    # large has no `ward` race at all, and one with wards need not elect any at large.
    if "ward" not in races and "atlarge" not in races:
        problems.append(f"{census_id}: no council race of either kind")
    # The stems are the scopes, so a race that arrived under the wrong key would put an
    # at-large contest into a ward-scoped field and go unnoticed in the output.
    for stem, scoped_at_large in (("ward", False), ("atlarge", True)):
        for race in races.get(stem, []):
            if race["at_large"] != scoped_at_large:
                problems.append(
                    f"{census_id}: {race['office']!r} is under {stem} but is "
                    f"{'at-large' if race['at_large'] else 'ward'}-scoped"
                )

    races_by_mun[census_id] = races

# --- checks -------------------------------------------------------------------------
#
# Two at-large races under one stem would be merged into a single list, which no
# municipality here does any more - Sarnia's second city-wide slate is an upper-tier seat
# and sits in reg_coun - and which would silently double a municipality whose data had
# been entered twice. Two ward-scoped races must never both claim a ward: Chatham-Kent's
# two tiers are disjoint by design, each ward sitting in exactly one.
for census_id, races in races_by_mun.items():
    for stem, race_list in races.items():
        seen = {}
        for race in race_list:
            for label in race["districts"]:
                if label == AT_LARGE:
                    continue
                if label in seen:
                    problems.append(
                        f"{census_id}: two {stem} races both cover {label!r} "
                        f"({seen[label]!r} and {race['office']!r})"
                    )
                seen[label] = race["office"]

if problems:
    print(f"{len(problems)} problem(s); nothing written:", file=sys.stderr)
    for p in problems:
        print("  - " + p, file=sys.stderr)
    sys.exit(1)


# --- project onto what a respondent is served ---------------------------------------


def wards_of(census_id):
    """Every ward a respondent can answer with, plus "99" for no ward at all."""
    labels = set()
    for race_list in races_by_mun[census_id].values():
        for race in race_list:
            if not race["at_large"]:
                labels.update(race["districts"])
    return sorted(labels, key=name_sort_key) + [AT_LARGE]


def served(census_id, stem, ward):
    """The districts a respondent in `ward` is served under `stem`.

    An at-large race, plus the one ward district they live in. Never another ward.
    """
    out = []
    for race in races_by_mun[census_id].get(stem, []):
        district = race["districts"].get(AT_LARGE if race["at_large"] else ward)
        if district is not None:
            out.append((race, district))
    return out


def entry_for(census_id, ward):
    """This respondent's entry, already cut into its shared half and its ward half.

    Both halves are built stem by stem in the one pass, and each stem writes into exactly
    one of them - which is what makes the two disjoint by construction rather than by a
    second rule that could drift from the first. See SHARED_STEMS.
    """
    shared = {"names": {}, "fields": {}}  # decided municipality-wide
    own = {"names": {}, "fields": {}}  # decided by this ward

    for stem in STEMS:
        half = shared if stem in SHARED_STEMS else own
        names = half["names"]
        fields = half["fields"]
        got = served(census_id, stem, ward)
        merged = [name for _, district in got for name in district["names"]]
        # Sorted across the merge, so a Sarnia respondent gets one alphabetical list
        # rather than two runs of names that restart halfway down. Keyed by the name field
        # rather than the stem: the survey writes these out as <key>1, <key>2, ...
        names[NAME_FIELD[stem]] = sorted(merged, key=name_sort_key)

        # Blank where this respondent has no such race. That blank is what the flow reads
        # to skip the question, so it is load-bearing rather than cosmetic, and the
        # `unverified` check above is what keeps it honest: a served race with no verified
        # seat count would write the same blank for a question the respondent should see,
        # so it aborts the build instead of reaching the field.
        #
        # A bare `<stem>` flag sits alongside these for the three councillor stems, saying
        # the same thing as a 1/0 because the flow is easier to read for it - see
        # SERVED_FLAG_STEMS, which is also where the case for keeping the other two derived
        # is made. `smd`/`mmd` described the ward race's shape and are gone for good:
        # `mmd` was exactly `ward_max_votes > 1` and `smd` the complement of it, and no
        # question is piped on either.
        if stem in SERVED_FLAG_STEMS:
            fields[stem] = int(bool(got))

        seats = [district["seats"] for _, district in got]
        votes = [district["max_votes"] for _, district in got]
        counts = [len(district["names"]) for _, district in got]

        # `not got` is the only thing that blanks these now. A null seat count or max_votes
        # never reaches here - it aborted the build above - which is what makes blank mean
        # exactly one thing to the flow.
        if not got:
            fields[stem + "_accl"] = ""
        else:
            fields[stem + "_accl"] = int(
                all(n <= s for n, s in zip(counts, seats))
            )

        # mayor and dep_mayor write no max_votes at all - see SINGLE_VOTE_STEMS.
        if stem not in SINGLE_VOTE_STEMS:
            fields[stem + "_max_votes"] = sum(votes) if got else ""

    # The served-flags are written in the loop above, so each completes its stem's family
    # rather than standing outside it: ward, ward_accl, ward_max_votes.
    #
    # `ward` is the one worth a note of its own. Its 0 covers two different respondents:
    # one in Niagara Falls, North Bay or Sarnia, whose municipality runs no ward race at
    # all, and one who reached the question without giving a ward (the "99" entry). Neither
    # has a ward councillor to be asked about, and the first three are still served an
    # at-large councillor race, so `atlarge` is 1 for them where `ward` is 0.
    #
    # Not to be confused with __js_ward_name1.. in parse-wards.js, which are the ward
    # question's choices. That collision is why those were renamed: a flow that pipes
    # __js_ward next to __js_ward1 is one prefix-match away from a silent wrong answer.
    #
    # Uncompacted: the checks below read these dicts, and compaction turns them into
    # placeholder handles that only the serialiser can see through.
    return shared, own


def compact_entry(entry):
    """One half, with its name lists and its scalars folded onto single output lines."""
    return {
        "names": {field: compact(lst) for field, lst in entry["names"].items()},
        "fields": compact(entry["fields"]),
    }


municipalities = {}
max_names = {NAME_FIELD[stem]: 0 for stem in STEMS}
widest = {}
shared_field_keys = None
ward_field_keys = None

for census_id in sorted(races_by_mun):
    wards = {}
    shared = None
    for ward in wards_of(census_id):
        # Built before compaction so the numbers below can still see the lists.
        got = {stem: served(census_id, stem, ward) for stem in STEMS}
        for stem in STEMS:
            field = NAME_FIELD[stem]
            n = sum(len(d["names"]) for _, d in got[stem])
            if n > max_names[field]:
                max_names[field] = n
                # Name the ward only where the stem is decided by it; a mayoral list is
                # the same in every ward, so "Toronto Ward 1" would read as coincidence.
                by_ward = any(not r["at_large"] for r in races_by_mun[census_id].get(stem, []))
                widest[field] = (
                    f"{mun_names[census_id]} {ward}"
                    if by_ward and ward != AT_LARGE
                    else mun_names[census_id]
                )
        mun_shared, wards[ward] = entry_for(census_id, ward)

        # The whole premise of storing the shared half once: every ward has to agree on
        # it. If two ever disagreed, one ward's answer would be served to all of them and
        # nothing downstream could tell - see SHARED_STEMS, where the assumption is made.
        if shared is None:
            shared = mun_shared
        elif mun_shared != shared:
            die(
                f"{census_id}: ward {ward!r} disagrees with the other wards about a race "
                "that SHARED_STEMS holds is decided municipality-wide, so it cannot be "
                "stored once for the municipality. Move its stem out of SHARED_STEMS, or "
                "fix the race in data/raw/by-municipality/."
            )

    # Uncompacted for now; the checks below read these, and compaction is the last step.
    municipalities[census_id] = {
        "name": mun_names[census_id],
        "shared": shared,
        "wards": wards,
    }

# Every ward entry must carry the same scalar fields, or a respondent who switched
# municipality would keep one the new entry never overwrites. The shared halves have to
# agree with each other for the same reason, and the two halves have to stay disjoint:
# parse-candidates.js writes both out, so a field appearing in each would be written twice
# and the second value would silently win.
for census_id, mun in municipalities.items():
    shared_keys = tuple(sorted(mun["shared"]["fields"]))
    if shared_field_keys is None:
        shared_field_keys = shared_keys
    elif shared_keys != shared_field_keys:
        die(
            f"{census_id} writes a different set of shared fields than the rest: "
            f"{set(shared_keys) ^ set(shared_field_keys)}"
        )

    for ward, entry in mun["wards"].items():
        keys = tuple(sorted(entry["fields"]))
        if ward_field_keys is None:
            ward_field_keys = keys
        elif keys != ward_field_keys:
            die(
                f"{census_id} {ward!r} writes a different set of fields than the rest: "
                f"{set(keys) ^ set(ward_field_keys)}"
            )
        both = set(shared_keys) & set(keys)
        if both:
            die(f"{census_id} {ward!r} writes {sorted(both)} in both halves")
        both = set(mun["shared"]["names"]) & set(entry["names"])
        if both:
            die(f"{census_id} {ward!r} lists {sorted(both)} in both halves")

for mun in municipalities.values():
    mun["shared"] = compact_entry(mun["shared"])
    mun["wards"] = {ward: compact_entry(e) for ward, e in mun["wards"].items()}

# Counted from the input, not the output: a ward pair is stored once per ward it is drawn
# from, and every at-large list is repeated under each ward, so counting the output would
# report a much larger number than there are candidates.
distinct = sum(
    len(d["candidates"])
    for census_id, entry in raw.items()
    if census_id != "_meta"
    for race_list in entry["races"].values()
    for race in race_list
    for d in race["districts"].values()
)

built = date.today().isoformat()
doc = {
    "meta": {
        "version": version,
        "built": built,
        "retrieved": raw["_meta"]["retrieved"],
        "generated_by": "scripts/build-candidates-js.py - do not hand-edit",
        "municipalities": len(municipalities),
        "candidates": distinct,
        # stem -> the name field its candidates are written under. The two differ for the
        # councillor races: the scalars are ward/atlarge/reg_coun, the lists are
        # coun_ward1.., coun_atlarge1.., coun_reg1... Read this rather than assuming a
        # stem names both.
        "stems": compact(NAME_FIELD),
        "max_names": max_names,
        # Split by where the scalar is decided, matching the two halves of every
        # municipality entry. The survey writes their union; nothing downstream has
        # to care which half a field came from, but a reader of this file does.
        "fields": compact(
            {"shared": list(shared_field_keys), "ward": list(ward_field_keys)}
        ),
        "provisional": raw["_meta"]["provisional"],
        "schema": (
            "A lookup table, not a description of the elections: "
            "municipalities[census_id].shared and .wards[ward label|\"99\"] together hold "
            "everything the survey writes for a respondent who gave that municipality and "
            "ward. The two halves are disjoint and the survey writes both, so read their "
            "union; `shared` is the part the municipality decides for every ward alike - "
            "the mayoral, at-large councillor and deputy mayor races - held once instead "
            "of repeated in every ward entry, and meta.fields says which scalars fall "
            "where. `names` "
            "is the five candidate lists, \"LAST, First\", already merged across the races "
            "they are served and in localeCompare order, keyed by the field the survey "
            "writes them out as: mayor1.., coun_ward1.., coun_atlarge1.., coun_reg1.., "
            "dep_mayor1... One list is one contest - the ward councillor race and the "
            "at-large one are never merged, since their candidates, max_votes and "
            "acclamation are all their own. `fields` is every scalar, already final - a "
            "number, or \"\" where there is nothing to say - and is keyed by stem instead: "
            "`<stem>_accl` for each of mayor, ward, atlarge, reg_coun, dep_mayor, plus "
            "`<stem>_max_votes` for ward, atlarge and reg_coun only - mayor and dep_mayor "
            "are single-seat everywhere, so a max_votes for them would read 1 in every "
            "row. A blank in either family means the respondent has no such race, and is "
            "what the survey flow filters the question on; a served race never writes one, "
            "since an unverified seat count aborts the build. The three councillor stems - "
            "ward, atlarge, reg_coun - each also carry a bare `<stem>` served-flag: 1 where "
            "the respondent is served that race, 0 where they are not, which is the same "
            "fact as a non-blank accl in a form a survey flow can pipe. mayor and dep_mayor "
            "have no such flag. meta.stems maps one to the other, and is "
            "worth reading rather than guessing - the ward stem's candidate list is "
            "coun_ward1.., not ward1... Every ward entry "
            "carries the same `fields` keys, as does every `shared`. \"99\" is the entry "
            "for a respondent with no ward, and the only entry for a municipality that "
            "elects at large."
        ),
        "max_names_note": (
            "The longest list each field family can reach, and the municipality that sets "
            "it: "
            + ", ".join(
                f"{NAME_FIELD[stem]} {max_names[NAME_FIELD[stem]]} "
                f"({widest.get(NAME_FIELD[stem], '-')})"
                for stem in STEMS
            )
            + ". The survey flow declares that many embedded fields per family by hand, so "
            "adding a municipality with a longer list means adding fields to the flow."
        ),
    },
    "municipalities": municipalities,
}

header = f"""// Candidate data for the CMB 2026 Ontario municipal election study.
//
// GENERATED by scripts/build-candidates-js.py from data/raw/candidates-raw.json.
// Do not hand-edit: rebuild instead, and bump version.txt if the served file changes.
//
// Served from GitHub Pages, loaded by the survey header, and read by
// code/survey/parse-candidates.js in the survey repo.
//
// A lookup table: everything the survey writes is worked out at build time and stored
// under the municipality and ward that produce it, so the survey reads one entry and
// writes it out. See meta.schema below, and the build script for why it is shaped so.
//
// Version {version}, built {built}, candidate lists retrieved {raw["_meta"]["retrieved"]}.
"""

dest = os.path.join(VERSIONS, f"candidates-{built}-v{version}.js")
with open(dest, "w", encoding="ascii") as fh:
    fh.write(header)
    fh.write("window.CMB_CANDIDATES = ")
    fh.write(dump(doc))
    fh.write(";\n")

ward_entries = sum(len(m["wards"]) for m in municipalities.values())
print(f"wrote {os.path.relpath(dest, REPO)}")
print(
    f"  municipalities {len(municipalities)}  candidates {distinct}  "
    f"ward entries {ward_entries}  {os.path.getsize(dest) // 1024} KiB"
)
print(
    "  fields the flow must declare: "
    + "  ".join(f"{NAME_FIELD[stem]}1..{max_names[NAME_FIELD[stem]]}" for stem in STEMS)
)
for stem in STEMS:
    field = NAME_FIELD[stem]
    print(f"    {field:<13} widest: {widest.get(field, '-')}")
print("  plus the scalars, shared: " + " ".join(shared_field_keys))
print("             and per ward: " + " ".join(ward_field_keys))
