#!/usr/bin/env python3
"""Build the survey-facing candidate file from data/raw/candidates-raw.json.

Usage: python3 scripts/build-candidates-js.py

Takes no arguments and, like the other scripts here, resolves the repo root from its own
path so it can be run from any working directory.

Inputs
  data/raw/candidates-raw.json
      Generated by scripts/build-candidates-raw.py. The source of truth for candidates.
  data/candidate-data-versions/version.txt
      The version number to stamp into the filename and into meta.version.

Output
  data/candidate-data-versions/candidates-{YYYY-MM-DD}-v{VERSION}.js
      Assigns a nested object to window.CMB_CANDIDATES. Loaded by the survey header and
      read by code/survey/parse-candidates.js in the survey repo.

This replaces scripts/parse-js.R, which wrapped a flat CSV in a template literal. The CSV
could not survive this data: `position` had room for only `mayor` and `council`, but 20 of
the 38 municipalities run more than one council race, and two of the values that would have
to go in it - Brampton's "Wards 1, 5" and Guelph's "RAMOS, JR." - contain the delimiter.

Shape
  window.CMB_CANDIDATES = {
    meta: {...},
    municipalities: {
      "<census_id>": {
        name: "Ottawa",
        races: {
          mayor|coun|reg_coun|dep_mayor: [
            {
              office: "Councillor",          // as published
              scope: "ward"|"at-large",
              districts: {
                "<ward label>"|"99": {
                  seats: 1,                  // null where the seat count is unverified
                  max_votes: 1,              // names a voter may mark; null likewise
                  n: 7,                      // candidates on file
                  accl: 0|1|null,            // n <= seats; null when seats is null
                  pair: "Wards 1, 5",        // only on a district split out of a ward pair
                  candidates: [{last, first}, ...]
                }
              }
            }
          ]
        }
      }
    }
  };

Four race stems, because the survey writes four families of embedded fields. `ward` and
`atlarge` both become `coun`: they are the same question to a respondent - who represents
you on council - and Thunder Bay, which runs both, gives its voters two councillor ballots
rather than two kinds of councillor. The stems stay arrays so a municipality with two
races of one kind keeps them apart: Sarnia elects City and City-County councillors in
separate at-large contests, and Chatham-Kent runs two ward tiers with different magnitudes.

`seats` sits on the district, not the race, for that Chatham-Kent reason - six of its wards
elect two councillors and two elect one.

At-large districts are keyed "99", the code data/csv/TEST_ab-cands.csv used for "this
municipality has no wards"; the survey passes "99" when the ward question was skipped, so
the lookup is the same one either way.

Ward pairs are split into the wards they are drawn from, so the survey can look a district
up by the ward the respondent actually answered. Brampton elects both its City and its
Regional councillors from five pairs, and Clarington its Regional councillors from two;
both keep the pair label in `pair`. The rule is the one ward-links.test.js already uses:
take the numbers out of the label.

The output is pure ASCII: non-ASCII characters are written as \\uXXXX escapes. The file is
served from GitHub Pages and loaded by a <script src> with no charset attribute, so the
browser is left to guess an encoding - and one wrong guess would turn "Ward 1 Orléans
East-Cumberland" into a string that no longer matches the ward the survey embedded.
"""
import json
import os
import re
import sys
from datetime import date

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "data", "raw", "candidates-raw.json")
VERSIONS = os.path.join(REPO, "data", "candidate-data-versions")
VERSION_FILE = os.path.join(VERSIONS, "version.txt")

# Raw race key -> the embedded-field stem the survey writes for it.
STEM = {
    "mayor": "mayor",
    "ward": "coun",
    "atlarge": "coun",
    "regional councillor": "reg_coun",
    "deputy mayor": "dep_mayor",
}
STEMS = ["mayor", "coun", "reg_coun", "dep_mayor"]

# The key for "no ward" - both an at-large district here and the value the survey sends
# when it never asked the ward question.
AT_LARGE = "99"

# ward-links.js is the survey-facing name list and calls 3553005 "Greater Sudbury"; the
# census calls it "Greater Sudbury / Grand Sudbury". Matching is on census_id, so this is
# cosmetic - it keeps the console logs from the two scripts reading the same.
NAME_OVERRIDE = {"3553005": "Greater Sudbury"}


def die(*msgs):
    for m in msgs:
        print(f"Error: {m}", file=sys.stderr)
    sys.exit(1)


def split_ward_pair(label):
    """"Wards 1, 5" -> ["Ward 1", "Ward 5"]. Same rule as ward-links.test.js."""
    return ["Ward " + n for n in re.findall(r"\d+", label)]


# --- serialisation ------------------------------------------------------------------
#
# json.dumps(indent=2) would put every candidate's two fields on two lines of their own,
# which turns 1,467 candidates into several thousand lines of scrollback. Candidates are
# dumped compactly instead and spliced back in, so the file stays readable: one candidate
# per line, everything above them indented.
_COMPACT = {}


def compact(obj):
    key = f"@@compact:{len(_COMPACT)}@@"
    _COMPACT[key] = json.dumps(obj, ensure_ascii=True, separators=(", ", ": "))
    return key


def dump(obj):
    text = json.dumps(obj, indent=2, ensure_ascii=True)
    for key, value in _COMPACT.items():
        text = text.replace(json.dumps(key), value)
    return text


# --- build --------------------------------------------------------------------------

if not os.path.exists(SRC):
    die(f"no such file: {SRC}", "run scripts/build-candidates-raw.py first")

if not os.path.exists(VERSION_FILE):
    die(f"no such file: {VERSION_FILE}")

with open(SRC, encoding="utf-8") as fh:
    raw = json.load(fh)

with open(VERSION_FILE, encoding="utf-8") as fh:
    version = fh.read().strip()

if not version:
    die(f"no version number found in {VERSION_FILE}")

problems = []
unverified = []
municipalities = {}

for census_id in sorted(k for k in raw if k != "_meta"):
    entry = raw[census_id]
    races = {}

    for race_key, race_list in entry["races"].items():
        stem = STEM.get(race_key)
        if stem is None:
            problems.append(f"{census_id}: unknown race key {race_key!r}")
            continue

        for race in race_list:
            at_large = race.get("district_scope") == "At-large"
            seats = race.get("seats_per_district")
            # Seats filled and names a voter may mark are two different measures that
            # happen to coincide in every race in the study today - tests/structure-csv.
            # test.js is the tripwire for that changing. Both are carried so the survey
            # never has to stand one in for the other.
            max_votes = race.get("max_votes")
            districts = {}

            for label, district in race["districts"].items():
                candidates = [
                    compact({"last": c["last_name"], "first": c["first_name"]})
                    for c in sorted(
                        district["candidates"],
                        key=lambda c: (c["last_name"], c["first_name"]),
                    )
                ]
                n = len(candidates)
                record = {
                    "seats": seats,
                    "max_votes": max_votes,
                    "n": n,
                    "accl": None if seats is None else int(n <= seats),
                    "candidates": candidates,
                }
                if seats is None:
                    unverified.append(f"{entry['csdname']} {race_key} ({n} candidates)")

                # A ward pair is stored under each ward it is drawn from: a respondent
                # answers with the one they live in, and both look up the same ballot.
                if race.get("district_scope") == "Ward-pair":
                    wards = split_ward_pair(label)
                    if not wards:
                        problems.append(
                            f"{census_id}: cannot split ward pair {label!r}"
                        )
                        continue
                    for ward in wards:
                        if ward in districts:
                            problems.append(
                                f"{census_id}: {race_key} district {ward!r} "
                                f"claimed twice (from {label!r})"
                            )
                        districts[ward] = dict(record, pair=label)
                else:
                    key = AT_LARGE if at_large else label
                    if key in districts:
                        problems.append(
                            f"{census_id}: {race_key} district {key!r} claimed twice"
                        )
                    districts[key] = dict(record)

            races.setdefault(stem, []).append(
                {
                    "office": race["office"],
                    "scope": "at-large" if at_large else "ward",
                    "districts": districts,
                }
            )

    if "mayor" not in races:
        problems.append(f"{census_id}: no mayoral race")
    if "coun" not in races:
        problems.append(f"{census_id}: no council race")

    municipalities[census_id] = {
        "name": NAME_OVERRIDE.get(census_id, entry["csdname"]),
        "races": {stem: races[stem] for stem in STEMS if stem in races},
    }

# --- checks -------------------------------------------------------------------------
#
# Two at-large races under one stem would be merged by the survey into a single list, which
# is right for Sarnia (two councillor contests on one ballot) but would silently hide a
# municipality whose data had been double-counted. Ward-scoped districts must not collide
# across the races of a stem for the same reason.
for census_id, mun in municipalities.items():
    for stem, race_list in mun["races"].items():
        seen = {}
        for race in race_list:
            for label in race["districts"]:
                if label in seen and label != AT_LARGE:
                    problems.append(
                        f"{census_id}: two {stem} races both cover {label!r} "
                        f"({seen[label]!r} and {race['office']!r})"
                    )
                seen[label] = race["office"]

# Every district must be reachable: a ward-scoped race and an at-large race under the same
# stem are both served to a respondent, but two ward-scoped races must divide the
# municipality the same way or a ward would get one race's candidates and not the other's.
for census_id, mun in municipalities.items():
    for stem, race_list in mun["races"].items():
        ward_races = [r for r in race_list if r["scope"] == "ward"]
        if len(ward_races) < 2:
            continue
        # Chatham-Kent's two ward tiers are disjoint by design - each ward sits in exactly
        # one tier - so the check is that no ward is in two tiers, not that they match.
        counts = {}
        for race in ward_races:
            for label in race["districts"]:
                counts[label] = counts.get(label, 0) + 1
        for label, count in counts.items():
            if count > 1:
                problems.append(
                    f"{census_id}: ward {label!r} appears in {count} {stem} races"
                )

if problems:
    print(f"{len(problems)} problem(s); nothing written:", file=sys.stderr)
    for p in problems:
        print("  - " + p, file=sys.stderr)
    sys.exit(1)


# --- how many fields the survey flow has to declare ---------------------------------
#
# The flow declares mayor1..N, coun1..N and so on by hand, so the build states the N it
# would take. Counted the way the survey counts: every race under a stem that a respondent
# in that ward would be served, at-large races included, summed.
def wards_of(mun):
    labels = set()
    for race_list in mun["races"].values():
        for race in race_list:
            if race["scope"] == "ward":
                labels.update(race["districts"])
    return sorted(labels) or [AT_LARGE]


def served(mun, stem, ward):
    """The districts a respondent in `ward` is served under `stem`."""
    out = []
    for race in mun["races"].get(stem, []):
        district = race["districts"].get(AT_LARGE if race["scope"] == "at-large" else ward)
        if district is not None:
            out.append(district)
    return out


max_names = {stem: 0 for stem in STEMS}
widest = {}
for census_id, mun in municipalities.items():
    for ward in wards_of(mun):
        for stem in STEMS:
            races = mun["races"].get(stem, [])
            n = sum(d["n"] for d in served(mun, stem, ward))
            if n > max_names[stem]:
                max_names[stem] = n
                # Name the ward only where the stem is decided by it; a mayoral list is
                # the same in every ward, so "Toronto Ward 1" would read as a coincidence.
                by_ward = any(r["scope"] == "ward" for r in races)
                widest[stem] = (
                    f"{mun['name']} {ward}"
                    if by_ward and ward != AT_LARGE
                    else mun["name"]
                )

# Counted from the input, not the output: a ward pair is stored once per ward it is drawn
# from, so counting the output would report Brampton's and Clarington's candidates twice.
distinct = sum(
    len(d["candidates"])
    for census_id, entry in raw.items()
    if census_id != "_meta"
    for race_list in entry["races"].values()
    for race in race_list
    for d in race["districts"].values()
)

built = date.today().isoformat()
doc = {
    "meta": {
        "version": version,
        "built": built,
        "retrieved": raw["_meta"]["retrieved"],
        "generated_by": "scripts/build-candidates-js.py - do not hand-edit",
        "municipalities": len(municipalities),
        "candidates": distinct,
        "max_names": max_names,
        "provisional": raw["_meta"]["provisional"],
        "schema": (
            "municipalities[census_id].races[mayor|coun|reg_coun|dep_mayor] is an ARRAY of "
            "races; each race's districts are keyed by ward label, or \"99\" when the race "
            "is at-large. seats and max_votes sit on the district because Chatham-Kent's "
            "two ward tiers differ; they are separate measures - seats filled vs names a "
            "voter may mark - that coincide in every race here today. accl is n <= seats, "
            "or null where seats is unverified. A district carrying `pair` was split out "
            "of a ward pair and its candidates are also stored under the pair's other "
            "ward(s)."
        ),
        "max_names_note": (
            "The largest list a single respondent can be served for each stem, summed over "
            "every race they would see: "
            + ", ".join(f"{stem} {max_names[stem]} ({widest.get(stem, '-')})" for stem in STEMS)
            + ". The survey flow declares that many embedded fields per stem by hand, so "
            "adding a municipality with a longer list means adding fields to the flow."
        ),
    },
    "municipalities": municipalities,
}

if unverified:
    doc["meta"]["unverified_seats"] = (
        "Races whose seat count is not yet verified upstream, so accl is null and the "
        "survey leaves the acclamation field blank rather than guessing: "
        + "; ".join(sorted(set(unverified)))
        + ". See the structure_gap notes in data/raw/by-municipality/."
    )

header = f"""// Candidate data for the CMB 2026 Ontario municipal election study.
//
// GENERATED by scripts/build-candidates-js.py from data/raw/candidates-raw.json.
// Do not hand-edit: rebuild instead, and bump version.txt if the served file changes.
//
// Served from GitHub Pages, loaded by the survey header, and read by
// code/survey/parse-candidates.js in the survey repo.
//
// Version {version}, built {built}, candidate lists retrieved {raw["_meta"]["retrieved"]}.
// See meta.schema below for the shape and meta.provisional for what the lists are worth.
"""

dest = os.path.join(VERSIONS, f"candidates-{built}-v{version}.js")
with open(dest, "w", encoding="ascii") as fh:
    fh.write(header)
    fh.write("window.CMB_CANDIDATES = ")
    fh.write(dump(doc))
    fh.write(";\n")

print(f"wrote {os.path.relpath(dest, REPO)}")
print(f"  municipalities {len(municipalities)}  candidates {distinct}")
print(
    "  fields the flow must declare: "
    + "  ".join(f"{stem}1..{max_names[stem]}" for stem in STEMS)
)
for stem in STEMS:
    print(f"    {stem:<10} widest: {widest.get(stem, '-')}")

if unverified:
    print(f"\n  seat count unverified for {len(set(unverified))} race(s); accl left null:")
    for u in sorted(set(unverified)):
        print(f"    {u}")
