#!/usr/bin/env python3
"""Build data/raw/candidates-raw.json from the hand-collected per-municipality files.

Usage: python3 scripts/build-candidates-raw.py

Takes no arguments and, like the R scripts, resolves the repo root from its own path so it
can be run from any working directory.

Inputs
  data/raw/by-municipality/<census_id>-<slug>.json
      Hand-maintained. One file per municipality, holding candidate names exactly as the
      source published them, plus the notes for that municipality. Never generated.
  notes/councillor-election-structure.csv
      Generated by R/get-municipal-data.R. Supplies district_source_url, max_votes_source
      and the ballot structure for every race.

Output
  data/raw/candidates-raw.json
      Generated - do not hand-edit. Written only after every check below passes, so a
      failed run leaves the previous file untouched.

Checks (all fatal)
  - every municipality in the structure CSV has a file, and no file is for a municipality
    that is not in it
  - every race in the structure CSV is present, matched on office and, where a
    municipality has two rows sharing an office, on n_districts and max_votes
  - every municipality has a mayoral race (mayors are excluded from the structure CSV by
    design, so they cannot be checked against it)
  - the number of districts collected matches n_districts
  - no district is empty and no candidate has an empty surname
  - no candidate record is a withdrawn nomination

Withdrawn nominations are not part of this dataset. They are filtered here as a guard, but
the inputs are expected to exclude them already; a hit is a fatal error, not a silent drop.
"""
import csv
import glob
import json
import os
import re
import sys

# Default collection date, used for every municipality file that does not carry its own
# notes.retrieved.
RETRIEVED = "2026-08-11"

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "data", "raw", "by-municipality")
STRUCT = os.path.join(REPO, "notes", "councillor-election-structure.csv")
DEST = os.path.join(REPO, "data", "raw", "candidates-raw.json")

# Race-type keys, in the order they are emitted.
RACE_KEYS = ["mayor", "atlarge", "ward", "regional councillor", "deputy mayor"]

SUFFIX = {"jr", "sr", "ii", "iii", "iv"}
PRONOUNS = re.compile(r",\s*(she|he|they|ze)/\w+\s*$", re.I)
WITHDRAWN = re.compile(r"withdraw", re.I)

problems = []


def norm(s):
    return re.sub(r"\s+", " ", (s or "")).strip()


def is_suffix(tok):
    return tok.lower().strip(".") in SUFFIX


def split_last_first(raw):
    """'Last, First'. Handles a suffix carrying its own comma: 'Ramos, Jr., Evaristo'."""
    parts = [p.strip() for p in raw.split(",")]
    if len(parts) >= 3 and is_suffix(parts[1]):
        return f"{parts[0]}, {parts[1]}", ", ".join(parts[2:])
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], ", ".join(parts[1:])


def split_first_last(raw):
    """'First Last'. A trailing suffix stays with the surname."""
    toks = raw.split()
    if not toks:
        return raw, ""
    if len(toks) == 1:
        return toks[0], ""
    suffix = toks.pop() if len(toks) > 2 and is_suffix(toks[-1]) else ""
    last = toks[-1]
    first = " ".join(toks[:-1])
    return (f"{last} {suffix}" if suffix else last), first


def split_caps_surname(raw):
    """Surname in CAPS, given name mixed case (Niagara Falls, Pickering, Waterloo).

    Falls back to first-last when a source is inconsistent - Pickering publishes one
    mayoral candidate in mixed case - or when the whole name is capitalised.
    """
    toks = raw.split()
    caps = [t for t in toks if len(t) > 1 and t == t.upper() and re.search(r"[A-ZÀ-Þ]", t)]
    if not caps or len(caps) == len(toks):
        return split_first_last(raw)
    i = next(i for i, t in enumerate(toks) if t in caps)
    return " ".join(toks[i:]), " ".join(toks[:i])


SPLITTERS = {
    "last_first": split_last_first,
    "pre_split": split_last_first,
    "caps_surname": split_caps_surname,
    "first_last": split_first_last,
}


def make_candidate(raw, fmt):
    raw = norm(raw)
    last, first = SPLITTERS[fmt](PRONOUNS.sub("", raw).strip())
    # Brampton publishes one candidate with '-' as a placeholder given name.
    if not re.search(r"\w", first):
        first = ""
    return {"name_raw": raw, "last_name": last.upper(), "first_name": first}


# --------------------------------------------------------------- structure CSV
struct = {}
with open(STRUCT, newline="", encoding="utf-8") as fh:
    for row in csv.DictReader(fh):
        struct.setdefault(row["census_id"], []).append(row)


def urls(cell):
    return [u.strip() for u in (cell or "").split(";") if u.strip()]


def find_row(cid, office, n_districts, max_votes):
    """Match a race to its structure-CSV row.

    Chatham-Kent has two rows sharing an office, distinguished only by how many districts
    they cover and how many names the ballot allows.
    """
    rows = [r for r in struct.get(cid, []) if r["office"] == office]
    if len(rows) <= 1:
        return rows[0] if rows else None
    for r in rows:
        if str(r["n_districts"]) == str(n_districts) and str(r["max_votes"]) == str(max_votes):
            return r
    return rows[0]


def build_race(cid, r, fmt, list_url):
    office = r["office"]
    row = find_row(cid, office, r.get("n_districts"), r.get("max_votes"))
    districts = {}
    for dname, names in r["districts"].items():
        cands = []
        for raw in names:
            if WITHDRAWN.search(raw):
                problems.append(f"{cid} {office} {dname}: withdrawn nomination in input: {raw!r}")
                continue
            c = make_candidate(raw, fmt)
            if not c["last_name"]:
                problems.append(f"{cid} {office} {dname}: empty surname for {raw!r}")
            cands.append(c)
        if not cands:
            problems.append(f"{cid} {office} {dname}: no candidates")
        districts[dname] = {"candidates": cands}

    expected = r.get("n_districts")
    if expected is not None and len(districts) != expected:
        problems.append(
            f"{cid} {office}: {len(districts)} districts collected, n_districts={expected}"
        )

    race = {
        "office": office,
        "district_scope": r.get("scope"),
        "n_districts": r.get("n_districts"),
        "seats_per_district": r.get("seats"),
        "max_votes": r.get("max_votes"),
        "block_vote": r.get("block_vote"),
        "sources": {
            "district_source_url": urls(row["district_source_url"]) if row else [],
            "max_votes_source": urls(row["max_votes_source"]) if row else [],
            "candidate_list_url": list_url,
        },
        "districts": districts,
    }
    if r.get("not_in_structure_csv") or (row is None and office != "Mayor"):
        race["not_in_structure_csv"] = True
    return race


# ------------------------------------------------------------------- assemble
out = {}
for path in sorted(glob.glob(os.path.join(SRC, "*.json"))):
    with open(path, encoding="utf-8") as fh:
        m = json.load(fh)
    cid = m["census_id"]
    fmt = m.get("name_format", "first_last")
    if fmt not in SPLITTERS:
        problems.append(f"{cid}: unknown name_format {fmt!r}")
        continue
    for key in m["races"]:
        if key not in RACE_KEYS:
            problems.append(f"{cid}: unexpected race key {key!r}")
    notes = dict(m.get("notes", {}))
    # A municipality collected on a different day states its own date; RETRIEVED is the
    # default for the rest, so the two cannot silently disagree.
    notes.setdefault("retrieved", RETRIEVED)
    races = {
        key: [build_race(cid, r, fmt, m.get("candidate_list_url")) for r in m["races"][key]]
        for key in RACE_KEYS
        if key in m["races"]
    }
    out[cid] = {"csdname": m["csdname"], "notes": notes, "races": races}

# ------------------------------------------------------------ coverage checks
missing = set(struct) - set(out)
extra = set(out) - set(struct)
if missing:
    problems.append(f"municipalities in the structure CSV with no input file: {sorted(missing)}")
if extra:
    problems.append(f"input files for municipalities not in the structure CSV: {sorted(extra)}")

for cid, rows in struct.items():
    if cid not in out:
        continue
    have = {race["office"] for rs in out[cid]["races"].values() for race in rs}
    for office in {r["office"] for r in rows} - have:
        problems.append(f"{cid} ({out[cid]['csdname']}): structure-CSV race {office!r} not collected")
    if "mayor" not in out[cid]["races"]:
        problems.append(f"{cid} ({out[cid]['csdname']}): no mayoral race collected")

if problems:
    print(f"{len(problems)} problem(s); {DEST} not written:", file=sys.stderr)
    for p in problems:
        print("  - " + p, file=sys.stderr)
    sys.exit(1)

# ----------------------------------------------------------------------- emit
doc = {
    "_meta": {
        "description": (
            "Candidate lists for every race in the Ontario municipalities in "
            "notes/councillor-election-structure.csv, keyed by StatCan census subdivision id."
        ),
        "generated_by": "scripts/build-candidates-raw.py - do not hand-edit",
        "retrieved": RETRIEVED,
        "municipalities": len(out),
        "provisional": (
            "Ontario nominations for the 2026 cycle close 2026-08-21 at 14:00, and the clerk's "
            "certified list follows by 16:00 on 2026-08-24. Every list here is an unofficial "
            "snapshot and is therefore incomplete - candidates may still file. Each "
            "municipality's collection date is its notes.retrieved: 2026-08-11 for all but "
            "North Bay and New Tecumseth, which joined the study on 2026-08-12. Markham, "
            "Vaughan and Waterloo each had only one mayoral candidate on file. Re-collect "
            "after certification for a final list."
        ),
        "schema": (
            "<census_id> -> {csdname, notes, races}. Each key under 'races' holds an ARRAY of "
            "race objects so a municipality with two races of the same type does not collapse: "
            "Sarnia has two at-large councillor races, and Chatham-Kent has two ward tiers "
            "with different max_votes. Race keys: mayor, atlarge, ward, "
            "'regional councillor', 'deputy mayor'."
        ),
        "candidate_fields": (
            "name_raw is the name exactly as published. last_name is upper-cased and first_name "
            "mixed case, following data/csv/TEST_ab-cands.csv. Sources publish names in three "
            "different shapes ('Last, First', 'First Last', and mixed-case given name with a "
            "CAPS surname); the shape used for each municipality is its name_format in "
            "data/raw/by-municipality/."
        ),
        "sources": (
            "district_source_url and max_votes_source are copied from "
            "notes/councillor-election-structure.csv for the matching race. candidate_list_url "
            "is the page the names were actually read from, which for many municipalities is "
            "one hop from district_source_url because that URL points at a ward-boundary or "
            "council-composition page rather than a candidate list."
        ),
        "withdrawn": "Withdrawn nominations are excluded from this dataset.",
        "known_gaps": (
            "Kitchener and Cambridge each publish an at-large Regional Councillor race with no "
            "row in council-races.csv, so it is absent from councillor-election-structure.csv "
            "too. Both are included here with seats/max_votes null and not_in_structure_csv "
            "true, since SOURCES.md lists both municipalities under at-large block vote."
        ),
    }
}
doc.update({k: out[k] for k in sorted(out)})

with open(DEST, "w", encoding="utf-8") as fh:
    json.dump(doc, fh, indent=2, ensure_ascii=False)
    fh.write("\n")

total = sum(
    len(d["candidates"])
    for m in out.values()
    for rs in m["races"].values()
    for r in rs
    for d in r["districts"].values()
)
races_n = sum(len(rs) for m in out.values() for rs in m["races"].values())
print(f"wrote {os.path.relpath(DEST, REPO)}")
print(f"  municipalities {len(out)}  races {races_n}  candidates {total}")
